version: "3.8"
services:

    backend:
        build: ./backend/
        image: ddiazsouto/backend-flask
        ports:
        - target: 5000
          published: 5000
          protocol: tcp

    frontend:
        build: ./frontend/
        image: ddiazsouto/frontend-flask
        ports:
        - target: 8080
          published: 8080
          protocol: tcp